### ISSUE TITLE
Fragments docs still use deprecated graphql-fragments package

### ISSUE THREAD

**Issue by bgentry** [apollographql/angular-docs#34]
On the [Angular 2 Fragments doc](http://dev.apollodata.com/angular2/fragments.html), the examples use the [graphql-fragments](https://github.com/apollographql/graphql-fragments) package, which is deprecated.

**Comment by Urigo** [comment]
Hi @bgentry !  :)
Thanks for the heads up...
Would you mind filing a PR for that?

**Comment by kamilkisiela** [comment]
@bgentry Feel free to contact me directly for any help with the PR (if you want to contribute of course)!

**Comment by bgentry** [comment]
I actually only noticed this because I was trying to find a single up-to-date example of how to handle fragments, but every single doc page recommends a different approach. I have no idea which one is considered the right one these days.

Even the core apollo client API docs seem to reference outdated methods for doing this.

So basically, I think you should just make a pass at this section on all your framework docs.

**Comment by stubailo** [comment]
@bgentry thanks for letting us know. The authoritative page about fragments right now is the `react` documentation. We tend to update that one first because the overwhelming majority of Apollo developers are using React, but we should see if we can set up something so that we don't forget to update the other pages. In particular it's really bad that the API docs are not automatically updated.

**Comment by kamilkisiela** [comment]
#35
